### ISSUE TITLE
Отсутствие прицела

### ISSUE THREAD

**Issue by ARMA-Servera-Brown** [salwador/MTA-DayZ-Ultimate#10]
Не появляется прицел при выходе из машины или любого транспортного средства, тогда когда тебе надо все сделать быстро. Например: пока он выходит из тачки ты начинаешь наводить прицел и его нет!

**Comment by salwador** [comment]
Событие не вызывается, если игрок прицеливается не выйдя из транспорта целиком. 
Посмотрим что можно будет придумать, для обхода проблемы.

![image](https://user-images.githubusercontent.com/12719219/30181082-75cf1bd6-9455-11e7-9edf-6a12a325d015.png)

**Comment by salwador** [comment]
Fixed in 1.2.27+
