### ISSUE TITLE
Система бессознания

### ISSUE THREAD

**Issue by CrabbyAdei71** [salwador/MTA-DayZ-Ultimate#100]
Попробовать подкорректировать систему с бессознания, оригинальнее будет лежачим себя чтоб перебинтовать можно было (глупо когда в одного пытаешься дать -4,-6 а тебя последний ложит, и встать ты не сможешь, пусть и есть малая вероятность, но кровотек не даст, он почти всегда срабатывает) либо можно попробывать впилить в жилет, который не открывает кровотек...

**Comment by salwador** [comment]
Ты без сознания, как бинтоваться собрался?

**Comment by Private1337** [comment]
salwador commented 3 days ago
Ты без сознания, как бинтоваться собрался?
____________________________________________________
Бинтануться после болевого шока.

**Comment by salwador** [comment]
@Private1337 встанешь и перебинтуешься, проблемы?

**Comment by salwador** [comment]
useless
