### ISSUE TITLE
Значок после использования аптечек

### ISSUE THREAD

**Issue by CrabbyAdei71** [salwador/MTA-DayZ-Ultimate#101]
Когда использовал маленькую аптечку, значок в правом углу присутствует, использовал среднюю и большую, его нет.

![mta-screen_2018-02-20_21-49-02](https://user-images.githubusercontent.com/31574768/36443084-d289c50a-1688-11e8-94d5-3b35c7b67140.png)
![mta-screen_2018-02-20_21-48-58](https://user-images.githubusercontent.com/31574768/36443085-d2afe7d0-1688-11e8-8850-08e9d15f9945.png)

![mta-screen_2018-02-20_21-49-50](https://user-images.githubusercontent.com/31574768/36443022-ab0aebd0-1688-11e8-9fde-5a1fc2967750.png)
![mta-screen_2018-02-20_21-49-56](https://user-images.githubusercontent.com/31574768/36443023-ab292d98-1688-11e8-9bcf-12065e8e27dc.png)

**Comment by salwador** [comment]
Здоровье при этом пополняется?

**Comment by CrabbyAdei71** [comment]
Да

**Comment by salwador** [comment]
Fixed in next versions
