### ISSUE TITLE
Неизвестный баг-

### ISSUE THREAD

**Issue by Private1337** [salwador/MTA-DayZ-Ultimate#102]
Приехал на зону,а тут такое
![mta-screen_2018-02-22_04-06-57](https://user-images.githubusercontent.com/36661937/36541673-4195b600-1811-11e8-9448-c7b741420961.png)
![mta-screen_2018-02-22_04-08-34](https://user-images.githubusercontent.com/36661937/36541674-41cd379c-1811-11e8-884d-23cea19731da.png)
![mta-screen_2018-02-22_04-06-56](https://user-images.githubusercontent.com/36661937/36541675-41f7e8c0-1811-11e8-8d31-a740a444de89.png)
![mta-screen_2018-02-22_04-10-14](https://user-images.githubusercontent.com/36661937/36541680-439f4ef2-1811-11e8-99d0-d83776b640fe.png)
![mta-screen_2018-02-22_04-11-11](https://user-images.githubusercontent.com/36661937/36541681-43ce41a8-1811-11e8-84cc-2b9c8405165f.png)
![mta-screen_2018-02-22_04-10-10](https://user-images.githubusercontent.com/36661937/36541683-440125e6-1811-11e8-9e22-4d0f30dc54f0.png)
Скорее всего,это из-за нестабильного интернета.

**Comment by salwador** [comment]
Версия GTA говно, либо комп. Сервер тут не при чём.
