### ISSUE TITLE
Баг с предметами на полу и с бесконечной загрузкой

### ISSUE THREAD

**Issue by Private1337** [salwador/MTA-DayZ-Ultimate#103]
Бывает такое,приезжает друг к тебе>>бросает лут на землю>>затем ты нажимаешь Е>>*Предмет не берется>>открываешь инвент и там курсор с безконечной загрузкой.

**Comment by salwador** [comment]
И как этот баг воспроизвести? Куда фиксить?

**Comment by KaSpEr04ek** [comment]
Бывает такое, как воспроизвести, даже не знаю, как говорится раз на раз не приходится, но случается иногда, что лут поднимаешь с земли, даже если на колёсико мыши нажимаешь, и всё, бесконечное колёсико крутится, и приходится перезайти

**Comment by Private1337** [comment]
Короч,поднял я чутка инфы об этом баге.
Вообщем,суть такая.
Если на земле лежит множество лута,и рядом находится человек.
То есть шанс воспроизведения данного бага.
Гуд лак <3
