### ISSUE TITLE
Не прошел урон из подствольного гранатомета.

### ISSUE THREAD

**Issue by CrabbyAdei71** [salwador/MTA-DayZ-Ultimate#105]
Слез с велосипеда и побежал на противника,он выстрелил из подствольного гранатомета, меня подбросило вверх, получил Anti-relog, но урон не прошел. 
https://www.youtube.com/watch?v=E8sCcRKq6gI&feature=youtu.be

**Comment by Private1337** [comment]
Это баг игры,не успел выйти из анимации?>>Урон не прошел.
Я сам лично встречался с таким багом.
