### ISSUE TITLE
Фикс респавна "Heli Crash" в карьере

### ISSUE THREAD

**Issue by Private1337** [salwador/MTA-DayZ-Ultimate#106]
Получается то что хели краш респавнится на самом,будем называть этот грузовичок "бурито",и получается месиво,-фпс,-уши,искры.Вообщем полное аниме.
Прошу фиксануть респавн
![mta-screen_2018-03-26_04-24-28](https://user-images.githubusercontent.com/36661937/37951287-1d08e568-31c6-11e8-9cc5-82074da764ed.png)

**Comment by Private1337** [comment]
Внимание на фпс.

**Comment by salwador** [comment]
Насколько знаю - транспорт там не спавнится. :thinking: 
Вероятно его там оставили, после чего - отспавнился краш.

**Comment by Jakob227** [comment]
@salwador , там как раз и спаунится GMC Van 1983, сам проверь. Я сколько не играю, он на всех серверах 24/7 стоит на этом спауне.
