### ISSUE TITLE
Не баг,а скорее всего просто недочет в обнове.

### ISSUE THREAD

**Issue by Private1337** [salwador/MTA-DayZ-Ultimate#107]
Думаю объяснять не надо...
![mta-screen_2018-03-27_04-02-59](https://user-images.githubusercontent.com/36661937/37951391-75128d90-31c6-11e8-99f8-67eca1ea9c95.png)

**Comment by Private1337** [comment]
внимание на "на подсказку"

**Comment by salwador** [comment]
Нет смысла сдвигать подсказку
