### ISSUE TITLE
Вернуть или фиксануть возможность писать личные сообщение игрокам.

### ISSUE THREAD

**Issue by Private1337** [salwador/MTA-DayZ-Ultimate#108]
Суть в том,что раньше можно было писать в локал чат:/msg Vasya_Pupkin онимэ?(Это пример,не приставайте,пж).
А сейчас мы пишем в локал чат,в глобал чат,и даже в крики,Нет,ничего не происходит.
Та же помарка с /time.

**Comment by Private1337** [comment]
Восможность*

**Comment by Private1337** [comment]
Что то у меня с клавиатурой не то.

**Comment by salwador** [comment]
> DayZ
> msg
> time

Серьёзно? Научитесь пользоваться часами и рацией.
