### ISSUE TITLE
Дополнение к игре.

### ISSUE THREAD

**Issue by Private1337** [salwador/MTA-DayZ-Ultimate#109]
![mta-screen_2018-03-08_10-14-52](https://user-images.githubusercontent.com/36661937/37951793-e0106922-31c7-11e8-95a8-689bfcf01579.png)
Фикс рюкзаков:West,Патрульный Рюкзак и Штурмовой.(Как-то так)
Ибо выглядит неприятно.

**Comment by salwador** [comment]
Влом координаты настраивать, ещё полтора года назад было введено :rofl:

**Comment by amingixds** [comment]
Добавьте вид от первого лица

**Comment by salwador** [comment]
@amingixds а ещё чё?

**Comment by salwador** [comment]
Done in 1.4
