### ISSUE TITLE
Баг с инвентарём трупа

### ISSUE THREAD

**Issue by NeEvilMuffin** [salwador/MTA-DayZ-Ultimate#11]
Если юзануть аптечку в тот момент, когда умираешь, к примеру: у вас 40 крови и вы юзнули медкит, аптечка не успеет поднять кол-во крови, и вы умрёте, и тогда вместо надписи: "вы умерли", камера будет подниматся вверх, итак, после перезахода на сервер, ваш труп магическим образом становится пустым, и если в него заглянуть, слоты будут 0/0 или 0/(кол-во ваших слотов на момент смерти, к примеру 48, 0/48), такие дела, так же есть такая фича, если при поднятии камеры не перезаходить, то ваш друг/тиммате сможет залутать вас
З.Ы. скрина нет

**Comment by salwador** [comment]
@NeEvilMuffin 4 попытки, баг не воспроизводится.

**Comment by NeEvilMuffin** [comment]
Тогда хз, с чем связан данный баг

**Comment by Jakob227** [comment]
Это бывает вообще рандомно.

**Comment by salwador** [comment]
Не встречалось уже давно.
