### ISSUE TITLE
Добавить новое ТС

### ISSUE THREAD

**Issue by MoHax2018** [salwador/MTA-DayZ-Ultimate#112]
Добавить пикап, на который взади можно устанавливать пулемёт, так же, добавить пулемёт + ленты на него. Прикольно бы было что бы рассекать на пикапе и стрелять сверху с пулика. Но делать это особо редким не стоит, так что бы как хама топ игроки в базу загнали и они там просто стоят для красоты, а сделать это доступным. Например сделать такую вещь на хамак, что бы можно было ставить пулик, там даже под это место есть, и сделать пару видов пикапов под этот пулик.

**Comment by salwador** [comment]
Нет.
