### ISSUE TITLE
Локализация контента

### ISSUE THREAD

**Issue by NeEvilMuffin** [salwador/MTA-DayZ-Ultimate#113]
Униформа и 2 головных убора из апдейта в134 не переведены на русский язык
*Civilian cap [Flecktarn] / Бейсболка [Flecktarn] (название этого камо не переводится)
![1](https://user-images.githubusercontent.com/31744538/38167954-a87f5700-3548-11e8-9e17-894f35aaaf13.PNG)
*Civilian cap [Forest] / Бейсболка [Лесной]
![2](https://user-images.githubusercontent.com/31744538/38167980-32cf928a-3549-11e8-994c-f5e89ed5c1ac.PNG)
*Survivour clothing [Forest] / Одежда выжившего [Лесной]
![3](https://user-images.githubusercontent.com/31744538/38167995-60669270-3549-11e8-8d6b-3e837949e7cd.PNG)
*ACR Black / ACR Чёрная (чёрный) !!!возможно так и задумано, но я чёт хз!!!
![4](https://user-images.githubusercontent.com/31744538/38168018-e04c6db6-3549-11e8-9481-ec13f779e264.PNG)
P.S. Не переведены только названия

**Comment by salwador** [comment]
Fixed in 1.4.3
