### ISSUE TITLE
Иконка СВД в инвентаре

### ISSUE THREAD

**Issue by NeEvilMuffin** [salwador/MTA-DayZ-Ultimate#114]
Так как у СВД сменили гилли накидку на ствол, иконка и визуал стали отличаться, думаю ошибка не серьёзная, но в глаза иногда бросается
*Визуал
![mta-screen_2018-04-01_01-18-26](https://user-images.githubusercontent.com/31744538/38168049-e10127fa-354a-11e8-9a13-12bbd1974a05.png)
*Иконка
![default](https://user-images.githubusercontent.com/31744538/38168057-09f26142-354b-11e8-96af-bf7b505ddc25.PNG)

**Comment by Private1337** [comment]
Бред чот

**Comment by NeEvilMuffin** [comment]
почему бред?

**Comment by salwador** [comment]
Так то да, позже сменю.
