### ISSUE TITLE
Не показывается ник после обновления

### ISSUE THREAD

**Issue by Jakob227** [salwador/MTA-DayZ-Ultimate#116]
Суть в том, что если у человека не видно хоть какой-то части тела (как я заметил), то его ник даже если отображается, то не сразу, и это сильно бесит. 
Пример: https://youtu.be/WZqqkp2RKkU (смотреть можно с 20 с.)

P.S. Если нужно будет, то я могу ещё таких примеров накидать.

**Comment by salwador** [comment]
Fixed in 1.3.5
