### ISSUE TITLE
Небольшой текстурный баг с хэликом.

### ISSUE THREAD

**Issue by Jakob227** [salwador/MTA-DayZ-Ultimate#12]
Я заметил, что у БНП и хэликов нет дыма, который должен быть. Когда хэлик заспавнился на мосте, над дорогой ЛС-СФ, то он лежал на мосту, а дым был под мостом. И соответственно  дыма в других БНП и хэликах не видно, потому что он под землей.

**Comment by denisFo** [comment]
Скорее всего проблема с самой гта. У меня всегда все отлично

**Comment by Jakob227** [comment]
Так будет более понятно https://youtu.be/RazPobxPab4

**Comment by salwador** [comment]
Этого объекта не должно быть вообще там, видимо остался, когда его заменили.

**Comment by salwador** [comment]
Коднюк из под вертолётов удалён полностью, поскольку когда-то его хотели заменить на нормальный дым. Нормальный дым добавили, а его не удалили.
