### ISSUE TITLE
Странности локализации

### ISSUE THREAD

**Issue by NeEvilMuffin** [salwador/MTA-DayZ-Ultimate#120]
Сравнил названия разных жилетов на русском и английском языке, и заметил странные подмены при переводе, в (...) приведены "исправленные" варианты перевода на английский язык
1) _**Police vest / Бронежилет**_ ( на англ можно перевести как _**Kevlar vest**_ )
![a](https://user-images.githubusercontent.com/31744538/38257769-8ffe2530-3769-11e8-97a0-7a2e0454bcb6.PNG)
![a](https://user-images.githubusercontent.com/31744538/38257772-91a734e4-3769-11e8-9eba-2e7e6e6ee174.PNG)
2) _**Hero vest / Разгруз. жилет "Woodland"**_ ( на англ можно перевести как _**Woodland vest**_ )
![a](https://user-images.githubusercontent.com/31744538/38257848-c6ad8422-3769-11e8-96b2-cdeb38bfdcf4.PNG)
![a](https://user-images.githubusercontent.com/31744538/38257851-c7d3a354-3769-11e8-9407-b87d7d97eb01.PNG)
3) _**Terror vest / разгруз. жилет "Oliva"**_ ( на англ можно перевести как _**Oliva vest**_ )
![a](https://user-images.githubusercontent.com/31744538/38258000-1c6c94b6-376a-11e8-813a-31d67ea82586.PNG)
![a](https://user-images.githubusercontent.com/31744538/38258006-1d822f64-376a-11e8-80c0-a7b7b0fd6a61.PNG)
4) _**Modular chest set / Полицейский жилет**_ ( на англ моно перевести как _**Police vest**_ )
![a](https://user-images.githubusercontent.com/31744538/38258118-53daea6a-376a-11e8-98c7-c06ac83fe8bf.PNG)
![a](https://user-images.githubusercontent.com/31744538/38258121-54f80b44-376a-11e8-986e-e6accd8f5b5f.PNG)
P.S. ещё есть странность с жилетом М2, к которому в англ версии добавили Military, но и так норм, т.к. он рил милитари.

**Comment by salwador** [comment]
Ничего странного, так и должно быть
