### ISSUE TITLE
Премиум Пакет

### ISSUE THREAD

**Issue by KaSpEr04ek** [salwador/MTA-DayZ-Ultimate#121]
Незнаю можно ли считать это полноценным багом, но в группе написаны вот такие характеристики:
9.1. 5% шанс получить Оранжевый хим. свет, после 15 дней использования. 
9.2. 10% шанс получить Оранжевый хим. свет, после 30 дней использования. 
9.3. 15% шанс получить Оранжевый хим. свет, после 60 дней использования. 
9.4. 20% шанс получить Оранжевый хим. свет, после 120 дней использования. 
9.5. 1% шанс получить 7 дней "Премиум" пакета на аккаунт, после 7 дней использования. 
9.6. 3% шанс получить 7 дней "Премиум" пакета на аккаунт, после 30 дней использования. 
9.7. 5% шанс получить 7 дней "Премиум" пакета на аккаунт, после 60 дней использования. 
А по факту, оранжевый хим.свет выпадает реже чем премиум пакет на 7 дней, бывает такое что ты месяц играешь, и за этот месяц тебе выпало 3-4 раза премиум пакет, а оранжевый только один раз, хотя по информации, должно быть всё, грубо говоря, наоборот

**Comment by KaSpEr04ek** [comment]
а забыл упомянуть, премиум я использую уже больше 120 дней

**Comment by salwador** [comment]
Рандом блять...
