### ISSUE TITLE
Баг

### ISSUE THREAD

**Issue by MoHax2018** [salwador/MTA-DayZ-Ultimate#122]
Когда у тебя в руках CZ, ты прыгаешь, а потом целишься получается вот что.
![mta-screen_2018-04-03_21-55-59](https://user-images.githubusercontent.com/37958333/38266624-cc688c32-3781-11e8-849c-929f7bf69729.png)
![mta-screen_2018-04-03_21-56-02](https://user-images.githubusercontent.com/37958333/38266629-d1675650-3781-11e8-8cb0-eb39071bce78.png)
![mta-screen_2018-04-03_21-56-03](https://user-images.githubusercontent.com/37958333/38266634-d46c86c2-3781-11e8-98be-3626fd2b05ff.png)

**Comment by Jakob227** [comment]
Это баг гта, его не исправить по-моему

**Comment by salwador** [comment]
Нормальное название где?

**Comment by salwador** [comment]
Fix in 1.4.3
