### ISSUE TITLE
/msg

### ISSUE THREAD

**Issue by Jakob227** [salwador/MTA-DayZ-Ultimate#123]
Либо я не знаю как писать в мсг, либо оно не работает просто, из-за нового чата. Когда ввожу в "Говорить" /msg *nick* [сообщение], то ничего не происходит

**Comment by MoHax2018** [comment]
Его же вырезали вроде

**Comment by salwador** [comment]
Потому что удалено.

**Comment by Private1337** [comment]
ну это п1здец конечно
