### ISSUE TITLE
People can run through buildings.

### ISSUE THREAD

**Issue by 666Taurus666** [salwador/MTA-DayZ-Ultimate#124]
This video will show you that people can run through buildings:
https://www.youtube.com/watch?v=Bl30o4gk6eY
It starts in the beginning the rest is irrelevant.
For example if you join CIT server, you go to a container inside naval, you can walk through it. The collision files of CIT server are active, its still in the cache. These people make their own collision file and replace it with a script so they can get through every building without you having the posibilty to go inside it.
the problem is client side, because 1 person can get in while the others can't.
There are more spots where you can go through buildings. but these are one of them.

**Comment by 666Taurus666** [comment]
This is not the only reason why this bug abusement is so big. People can put cars/tents inside those places. and no one else will be able to reach from it. you can also shoot outside, without people knowing you are there. And you are able to shoot them back.

**Comment by salwador** [comment]
MTA bug.

**Comment by 666Taurus666** [comment]
Do I need to report it at MTA dev's? I can do that.

**Comment by salwador** [comment]
@666Taurus666 yes, it's not a CIT or DayZ Ultimate bugs. All "COL's" bugs what opened after reconnect to server - it's a MTA "COL's" bugs after replace.

**Comment by 666Taurus666** [comment]
Yes, I understand it. I know whats happening. The COL's of the buildings are still in the cache of MTA, It's easy to fix for MTA developers. Just clean the cache. Thank you for helping. PS; can you delete this post so no people can abuse this bug?
