### ISSUE TITLE
Textures Bug

### ISSUE THREAD

**Issue by Private1337** [salwador/MTA-DayZ-Ultimate#125]
Думаю по названию понятно
Как я попал в данную текстуру
1.Пытался пробежать между цистерн
2.Меня втолкнуло в здание.
3.Дальше я ждал когда зайду ВЕЛИКИЕ ОДМЕНЫ.(2 часа,но одмен так и не пришел =(.  )
![mta-screen_2018-04-13_02-57-36](https://user-images.githubusercontent.com/36661937/38743379-257dc208-3f69-11e8-919e-71e00b8659fb.png)
![mta-screen_2018-04-13_02-57-41](https://user-images.githubusercontent.com/36661937/38743387-26feb362-3f69-11e8-9529-0a9931b43217.png)

**Comment by salwador** [comment]
Баг GTA, так можно воткнуться в половину зданий. А наличие модераторов и админов не относится к трекеру.
