### ISSUE TITLE
Баг со всеми взаимодействиями

### ISSUE THREAD

**Issue by KaSpEr04ek** [salwador/MTA-DayZ-Ultimate#13]
Только что произошёл фикс багов. а именно 8 сентября 2017 года, в 14:35 по МСК
Баг заключается в том что не возможно что либо сделать
К примеру, нельзя проверить время на трупе, когда его убили.
Нельзя залить топливо в транспорт.
Нельзя его починить ( транспорт )
И это как то напрягает

**Comment by salwador** [comment]
Во первых, нельзя было выполнить только первое действие
Во вторых, только что было исправлено и загружено на сервера
