### ISSUE TITLE
Скрол чатов.

### ISSUE THREAD

**Issue by Private1337** [salwador/MTA-DayZ-Ultimate#131]
Допустим,ты сидишь,листаешь чаты.
И тут ты пропустил нужный чат,тебе придётся листать опять.
Суть идеи в том,чтобы добавить "горячую клавишу" которая может скролить вид чата назад.
Я надеюсь не услышу типичного"Так листай внимательней" или что то в этом роду.
Удачи

**Comment by salwador** [comment]
Addded in 1.3.5
