### ISSUE TITLE
осветление(есус живи!11)

### ISSUE THREAD

**Issue by Private1337** [salwador/MTA-DayZ-Ultimate#135]
![mta-screen_2018-05-08_21-57-56](https://user-images.githubusercontent.com/36661937/40183675-9e3e196c-5a18-11e8-9acb-b7baa3853433.png)
Не знаю что это,наверное баг мта.Но вдруг часть это карты можно осветлить
![mta-screen_2018-05-09_00-37-55](https://user-images.githubusercontent.com/36661937/40184320-1f456dfc-5a1a-11e8-88c5-330d067f0e0a.png)
UPD:На случай если попытаются отмазаться что есть ПИКВ и ПНВ.
Оно там работает нестабильно.

**Comment by salwador** [comment]
Prelight в GTA такой.
