### ISSUE TITLE
Баг с взаимодействием

### ISSUE THREAD

**Issue by KaSpEr04ek** [salwador/MTA-DayZ-Ultimate#14]
В общем баг заключается в том, что после рестарта, и фикса багов на сегодня. как минимум на серве Brown невозможно что либо сделать с транспортым средством, не залить бензин, не починить его, даже время смерти на трупах нельзя посмотреть. и  нельзя попить воду с колонки или колодца

**Comment by salwador** [comment]
Повтор https://github.com/salwador/MTA-DayZ-Ultimate/issues/13
