### ISSUE TITLE
Проблема с админ панелью.

### ISSUE THREAD

**Issue by ENDELOVER** [salwador/MTA-DayZ-Ultimate#142]
При нажатии на "Player Name" в админ панели, сбивается список игроков. После чего, при телепорте к тому или инному игроку, модератора бросает к рандомным людям, полностью нарушается работоспособность админ панели. Помогает только релог.
https://www.youtube.com/watch?v=5zG2zG-nCrU

**Comment by Private1337** [comment]
палева 0
