### ISSUE TITLE
Проблемы с ПИКВ,ПНВ.

### ISSUE THREAD

**Issue by Private1337** [salwador/MTA-DayZ-Ultimate#146]
Нажав f11 когда активен ПИКВ,ПНВ края убираются.
Выглядит не очень.
![mta-screen_2018-07-15_05-40-40](https://user-images.githubusercontent.com/36661937/42733885-2a842d34-8864-11e8-9538-5b5526122a22.png)
![Uploading mta-screen_2018-07-15_05-40-41.png…]()

**Comment by salwador** [comment]
Не баг. Оставлять их на экране ещё более ущербно.
