### ISSUE TITLE
Баг с подствольником

### ISSUE THREAD

**Issue by SSDeshnik** [salwador/MTA-DayZ-Ultimate#148]
Когда едешь на подсаде на тачке и стреляешь с подствольника то подствольник не летит в ту сторону куда ты выстрелил, он блин взрывается у тебя перед лицом убивая тебя, тиммейтов и тачку

**Comment by SSDeshnik** [comment]
Сегодня постараюсь

**Comment by SSDeshnik** [comment]
Вот
Целился высоко но как бы высоко я не целился всё-равно взрывается рядом и убивает стрелка
Зачастую как я и сказал и тачку и тиммейтов

https://yadi.sk/i/W-b9lcP5mGtucw

**Comment by salwador** [comment]
Орнул, спасибо, надеюсь что исправим в ближайшее время.

**Comment by salwador** [comment]
Fixed in 1.4.3
