### ISSUE TITLE
 Игрок использует ошибки

### ISSUE THREAD

**Issue by JosiasMTA** [salwador/MTA-DayZ-Ultimate#149]
Я сообщал об этом игроку несколько раз.
Я жду ответа, потому что я вношу свой вклад в сервер.
https://www.youtube.com/watch?v=JtzcSSXYFUw&feature=youtu.be

**Comment by salwador** [comment]
Base protect was updated in 02.12, now players can't place tents/crates nearby bases. We know only one way for enter into base not from gate, and it should be fixed now.
