### ISSUE TITLE
текстурный баг в здании около санта мария 

### ISSUE THREAD

**Issue by MarShall823** [salwador/MTA-DayZ-Ultimate#15]
в здании напротив входа на колесо обозрения, есть балкончик в который можно залезть, а вылезти ну никак нельзя, раза 3 доставал игроков из этого бага 
![mta-screen_2017-09-08_16-08-38](https://user-images.githubusercontent.com/31770929/30215669-069c088a-94b1-11e7-8fae-86798f5a4ae4.png)
![mta-screen_2017-09-08_16-08-44](https://user-images.githubusercontent.com/31770929/30215668-06963162-94b1-11e7-8e77-3d4b7940f2c4.png)
![mta-screen_2017-09-08_16-09-09](https://user-images.githubusercontent.com/31770929/30215666-06904540-94b1-11e7-8640-2b3be9ff1f18.png)

**Comment by salwador** [comment]
Заебись. Мыло, ни карты, ни GPS.

**Comment by salwador** [comment]
Fix in 1.2.30+
