### ISSUE TITLE
New Libya flag

### ISSUE THREAD

**Issue by MohanedBeshena** [salwador/MTA-DayZ-Ultimate#154]
The flag of Libya was changed in 2011 and now this is the new science

![flag_of_libya_ 2011_combined svg](https://user-images.githubusercontent.com/47071843/52766977-a74ec980-3031-11e9-8ca6-2b0055178f4c.png)

**Comment by MohanedBeshena** [comment]
I know that mta he can changed

**Comment by MohanedBeshena** [comment]
I want you to report only

**Comment by salwador** [comment]
Replaced in 1.4.3 xD
