### ISSUE TITLE
Баг с анимацией и бегом

### ISSUE THREAD

**Issue by qqviki** [salwador/MTA-DayZ-Ultimate#155]
Не давно был забанен за этот баг , и дабы не повторять ошибок и не повторили те кто его знают , хочу что бы его убрали. Тут его не хочу расписывать всем , ведь это вносит дисбаланс. Не могу написать тебе в группу , убери меня с чс пожалуйста. Мой вк -https://vk.com/id526271880

**Comment by qqviki** [comment]
> Не давно был забанен за этот баг , и дабы тут его не расписывать всем , хочу что бы сальвадор его пофиксил , потому что не хочу его использовать сам и что бы использовали другие люди , знающие его , ведь это вносит дисбаланс. Не могу написать тебе в группу , убери меня с чс пожалуйста. Мой вк -https://vk.com/id526271880

**Comment by qqviki** [comment]
> бер

**Comment by qqviki** [comment]
> Не давно был забанен за этот баг , и дабы не повторять ошибок и не повторили те кто его знают , хочу что бы его убрали. Тут его не хочу расписывать всем , ведь это вносит дисбаланс. Не могу написать тебе в группу , убери меня с чс пожалуйста. Мой вк -https://vk.com/id526271880

**Comment by salwador** [comment]
:roll_eyes:
