### ISSUE TITLE
Превышение слотов из-за наполненных канистр

### ISSUE THREAD

**Issue by SteelVG** [salwador/MTA-DayZ-Ultimate#156]
![mta-screen_2019-03-05_21-57-57](https://user-images.githubusercontent.com/48126948/53829994-81627800-3f92-11e9-8ef4-0b39f9cc5b5d.png)

Превышение слотов из-за наполненных канистр
К примеру: Взяв с собой 40 пустых канистр, при наполнении водой/керосином и тд 
достигается превышение слотов инвентаря чем могло быть доступно
Рюкзак: Выживший  (46 слотов)
При наполнением жидкостью (33 канистры) +112.2 кг
46/112.2 кг

**Comment by salwador** [comment]
* Fixed in 1.4.4.2
