### ISSUE TITLE
[bug]На тестовом сервере были замечены баги: 

### ISSUE THREAD

**Issue by qqviki** [salwador/MTA-DayZ-Ultimate#160]
**Описание бага.**
Баги тестового сервера

1.Не меняется оружие , не колесиком , q e  тоже не работает , происходит само по себе , но очень мешает пвп.
2.Иконки того как починил с красных деталей , до более улучшенных не меняются - у одного из игроков показывало что все зеленное , у другого что все красное - какой то рассинхрон что ли , не знаю.
3. Звук выстрелов бывает падает на 50% , пока громкость звука мта стоит 100% , возможно связанно из-за вертолета ( ведь когда ты в нем звуки на 50% падают ,  или из-за чего то другого ) но сразу все работает нормально , а бывает они снижаются просто сами по себе
4. С зеленого двигателя до синего не улучшило с 20 ремок , не со всем баг , но не понятный     шанс улучшения какой то
5. На улучшенных деталях вертолета , я пролетал мимо зданий и бился об них минут 5 и даже больше , вертолет так и не сломался.
В целом задумка хорошая , но для новичков очень не понятная система станет и довольно сложная , ведь при старой они еле разбирались , а при новой думаю вообще все печально станет.

**Comment by salwador** [comment]
1. Подтверждено, такой баг есть.
2. Иконка не может не измениться, если предмет улучшен. :confused: 
3. Звуки выстрелов не изменялись, правка с громкостью вертолёта влияет только на него. :confused: (2)
4. 25% шанс улучшения. Кому-то с первого раза апает, кому-то и с 20 нет. С шансами всё нормально, сам вчера на тесте прокачивал зелёными. С премиумом шанс ещё +50% (и того 37,5%).
5. Проверим, на вертолётах и правда вроде никто не тестил.

- [ ] Баг с зависанием смены оружия.
- [ ] Урон вертолёта от столкновений.

**Comment by salwador** [comment]
ps. В следующий раз желательно раскидывать баги по отдельным issue.

**Comment by salwador** [comment]
Первый пофиксил, с повреждениями вертолёта проблем не вижу. При столкновениях наносится в среднем от 20 до 100 урона. 3245 - общее здоровье всех зелёных компонентов у вертолёта. :confused: 

Оставлю открытым, возможно какие-то условия мешают отрабатывать.

**Comment by qqviki** [comment]
На счет иконок я не знаю что именно происходит , но мы сели в вертолет и  у меня они все были красные , будто он сломан а у друга зеленные , что он прокачен как бы.

**Comment by salwador** [comment]
@qqviki , о каких иконках речь, что-то не врубаюсь?

**Comment by qqviki** [comment]
Ещё появился новый баг , когда нажимаешь E бывает сам по себе открывается инвентарь , хотя этого не должно быть т.к , многие на E Q меняют оружие.

**Comment by salwador** [comment]
* Fix bug with open inventory by "E" key
in 1.4.4.1
