### ISSUE TITLE
Bug Slot | MTA DAYZ ULTIMATE 1.4.4

### ISSUE THREAD

**Issue by PlayerMiller** [salwador/MTA-DayZ-Ultimate#161]
Суть бага в том, что при разборке авто/мото, можно разбирать спокойно не парясь за слоты.
То есть, если в сумме у меня 14 слотов, при разборке авто я могу выйти за лимит слотов.
Док-во: https://youtu.be/XDVrZe-LEgo

**Comment by salwador** [comment]
* Fixed in 1.4.4.2
