### ISSUE TITLE
*******Много разных багов ********

### ISSUE THREAD

**Issue by qqviki** [salwador/MTA-DayZ-Ultimate#163]
Описание различных багов

1. Баг с любым мотоциклом на сервере , при езде в 2 человека и двух кратном нажатии клавиши F , санчез или фривей , начинает ехать без звука.
2.Неоднократный баг со спамом анимации "сесть" , персонаж может просто без прерывно спамить эту анимацию тем самым уклоняясь от выстрелов или же падая с любого не очень высокого здания без урона , как по мне интервал 1-2 сек должен быть.
3.Баг с любыми патронами. Когда постреляешь и после делаешь перезарядку , происходит с баг неверным показаниям количества патронов, которые заряжены в магазин и если его не перезарядить а стрелять дальше , твои патроны в инвентаре не тратятся во все и так можно много раз делать . Как это баг происходит и можно ли сделать это специально не знаю , то таков есть.
4.Баг после смерти своей или же убийства кого либо : тут вообще понятия не имею что именно происходит , что бы так сделать специально , но после смерти у тебя поднимается камера вверх и достаточно просто перезайти , на сервер что бы появится со всем своим лутом который у тебя был , труп же будет пустым .
5.Есть очень много не закрытых багов на карте , это наверное не столь важно , но я написал на всякий , в случае необходимости могу все показать .
6)Баг с трупами: когда человек умирает допустим на мосту , то его труп проваливается под него постоянно , или же он умер на горе , и если под горой есть ЖД пути , он упадет на них
7) Баг с премиумом : когда время 00:00 , прему должно выдать его опыт за след. день и ящик , но у меня бывало такое , что его тупо не выдавало , и при перезаходе на сервер мне давало 2 ящика и опыта так же в х2 , не знаю как его сделать специально , но вот есть такой недочет , и лвл твоего према , бывает отображается некорректно.
8) Баг с сейфами : есть поставить палатку близко  к сейфу , что бы открывался инвентарь сейфа и палатки и нажимать быстро кнопку J подползая к сейфу , может открыться его инвентарь, пролутать его нельзя , но посмотреть т.к попускать слюни дает такой баг возможность.
9)Есть баг на базе H1 , если игрок который имеет доступ к базе поставит машину близко к стене на 1 этаже , то игрок который на улице может сесть в неё и тем самым попасть в базу.
Это ещё не все баги которые я нашёл , и решил расписать , но если это стоит того , я найду время написать ещё постик такой.

**Comment by salwador** [comment]
а теперь заново, так - как это должно быть
