### ISSUE TITLE
Баг с хилом

### ISSUE THREAD

**Issue by KaSpEr04ek** [salwador/MTA-DayZ-Ultimate#17]
В общем он заключается в том, что если я хочу своему другу залить кровь, то иногда не получается залить ему кровь, адже если у него всего 100 крови, и приходится другу перезаходить чтобы залить ему кровь

**Comment by salwador** [comment]
Причина бага какая?

**Comment by KaSpEr04ek** [comment]
Причины бага нет, просто не возможно залить кровь другу, ты к нему подходишь с пакетом крови в инвентаре у себя, а залить не можешь, и приходится или другу перезаходить, или давать аптечку, или бежать до больницы за аптечками

**Comment by denisFo** [comment]
Кстати да. Может быть и очень мало кровь, но пакет не применяется. Частенько встречается

**Comment by Buomag** [comment]
Очень часто такая херня, за последнюю неделю пытался соклану перелить кровь несколько раз, не получалось, просто не появлялась иконка

**Comment by salwador** [comment]
@Buomag i huli ne ponyatno?
![image](https://user-images.githubusercontent.com/12719219/31896850-1b3d21b4-b858-11e7-8ffd-a3bba51580c3.png)

**Comment by Buomag** [comment]
Та нихуя же не пофиксилось, вчера и пробовал)

**Comment by salwador** [comment]
@Buomag а нахуя тогда писать это? 

> за последнюю неделю пытался соклану перелить кровь

**Comment by Buomag** [comment]
Ну, за последнюю неделю включая вчера, значит хуйня не пофикшена

**Comment by salwador** [comment]
Модераторы, тестеры и игроки сообщают о том - что баг более не встречался.
Значит его исправление выполнено.
