### ISSUE TITLE
Текстурный баг и баг с зомби и людьми.

### ISSUE THREAD

**Issue by denisFo** [salwador/MTA-DayZ-Ultimate#19]
- [x] Текстурный баг: https://imgur.com/a/m6C71
- [x] Баг с людьми и зомби бывает при заходе в игру. После перезапуска, конечно, пропадает. Но все же https://imgur.com/a/HDBla

**Comment by Jakob227** [comment]
Да, тоже самое было.

**Comment by salwador** [comment]
Fix in 1.2.30+
Только текстурный баг

**Comment by salwador** [comment]
Возможно исправлен баг с трупами. Поскольку причину бага никто не написал - получаем кота в мешке.

**Comment by denisFo** [comment]
Причина же была названа. При падении с большой высоты.

**Comment by salwador** [comment]
@denisFo в каком месте?

**Comment by denisFo** [comment]
Ну как в каком месте? Везде. С крыши упал - разбился, все, труп в воздухе, или же с горы, такая же фигня, ну или вообще с вертолёта выпал

**Comment by salwador** [comment]
@denisFo а мы вообще не читаем, о каком баге речь, да? На этой странице ни слова не было сказано о трупах в воздухе...
