### ISSUE TITLE
Ship Event Bug

### ISSUE THREAD

**Issue by Michu2901** [salwador/MTA-DayZ-Ultimate#191]
Players killed on Ship event are droping on bottom of the ocean. 
- You can't see bot bodies but you can loot them. 
- You can't see players bodies and you can't loot them.

![Desktop Screenshot 2020 06 15 - 17 19 41 86](https://user-images.githubusercontent.com/66784249/84677859-9832a100-af2f-11ea-8d44-63afecb394f0.png)

**Comment by salwador** [comment]
@Michu2901 upload update, this should be fixed today. check please

**Comment by Michu2901** [comment]
When is next Ship Event?

**Comment by salwador** [comment]
@Michu2901 18:00 GMT+3

**Comment by Michu2901** [comment]
@salwador Ok. I will join and test it

**Comment by Michu2901** [comment]
@salwador All fixed. You can loot all the bodies.
