### ISSUE TITLE
Новый шлем и оружие

### ISSUE THREAD

**Issue by FullM4ster** [salwador/MTA-DayZ-Ultimate#193]
**1. Новый шлем**
   
     ●    На данный момент на проекте всего 2 часто используемых шлема HBM-O и Boulder, 
           изредко PASGT-M88 и маскировачный HBM.
           Можно добавить на проект новый шлем "Алтын", защитой от огнестрельного оружия 
           ~25% и от взрывчатки ~12%. Массой ~2 кг. (Найти данный шлем можно будет найти 
           только в "крашах").   
           https://imgur.com/a/3rWpzX4

**2. Новое оружие**

     ●  Так как уже достаточно оружия на патронах 5.56х45 предлогаю добавить новое оружие 
         АЦ-12 "Гроза" ССО на патронах 7.62х39 II (Без возможности установки модулей, найти 
         данное оружие можно будет только в airdrop'ах).
         Сделать её на уровне С7А2 или же CZ805, примерный урон обычной штурмовой 
         винтовки ~3600-3700 и ~42 по транспорту. Массой ~3.5 кг.

     ●  На проекте не так много снайперских винтовок и CheyTac M200 Intervention не 
         помешает.
         Примерным уроном обычной снайперской винтовки ~13500 и ~80 по транспорту. 
         Массой ~10 кг. (Найти данную винтовку можно будет в патруле или же в корабле.)

**Comment by salwador** [comment]
USA ~2005 годов - предлагать АЦ-12 и Алтын 🤔
