### ISSUE TITLE
Remington MSR

### ISSUE THREAD

**Issue by NeEvilMuffin** [salwador/MTA-DayZ-Ultimate#194]
**Описание бага.**
Не совсем баг, а скорее недоработка.
В реальности Remington MSR - винтовка с продольно-скользящим затвором, в простонародье "Болтовка", то есть её нужно взводить после каждого выстрела, в игре же она почему-то полностью автоматическая, хотя по логике должна быть чем-то вроде М24

**Воспроизведение.**
Взять MSR
Пострелять с неё

**Comment by salwador** [comment]
мафин ацтань
