### ISSUE TITLE
Дождь

### ISSUE THREAD

**Issue by denisFo** [salwador/MTA-DayZ-Ultimate#21]
Дождь на Ultimate это что то сверх мощное. Ибо как можно обьяснить его проникновение сквозь текстуры, такие как: некоторые здания(на скрине есть), палатки на военных точках и все виды контейнеров.
Скриншот: http://imgur.com/a/XZ2Y2

**Comment by salwador** [comment]
Не баг мода, а баг МТА. Дождь проходит сквозь все нестандартные объекты, а-ля маппинг.
