### ISSUE TITLE
Баг базы. Не работают ворота,не работают палатки,нельзя взять машину

### ISSUE THREAD

**Issue by razorque** [salwador/MTA-DayZ-Ultimate#210]
**Описание бага.**
Открыты базы,к которым у меня есть доступ,так же,нельзя открыть палатки (владелец базы дал доступ к палаткам). Так же когда сажусь в машину,она заводится,но передвигаться на ней нельзя. Ворота базы не закрываются.(на видео)

**Воспроизведение.**
Я не знаю как можно решить эту проблему. Тимейт сказал,что после рестарта произошёл этот баг.

**Последствия.**
Не могу взять лут,не могу взять машину

**Подтверждение**
https://youtu.be/_0OR1CtBVqA 

**Дополнительная информация**
Произошло после рестарта. Всё,больше информации нет. Так же можем пройти в дискорд,если нужно будет.

**Comment by salwador** [comment]
Исправлено.
