### ISSUE TITLE
Invisibility bug

### ISSUE THREAD

**Issue by Waffle228** [salwador/MTA-DayZ-Ultimate#215]
**Describe the bug**
This bug gives the person an ability to become invisible for everyone who is on the server at that moment. The people who reconnect after the bug is done can see where he is but no one else can. You can only kill the guys who are doing the bug if you reconnect to the server.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go sit in the vehicle for the driver(works in most vehicles)
2. The second player presses F to get in the driver position and quits the server while going to the car
3. Player in the driver seat stays in the vehicle and everyone else sees him in the vehicle but he is in a different place.

**Screenshots or videos**

Screenshot related to the video. It shows the guy that is bugged from the view of the person who reconnected to the server.

Here is the link to the video of the bug: https://www.youtube.com/watch?v=eczOF1Qghpc&feature=youtu.be

**Comment by salwador** [comment]
Fixed in latest patch
