### ISSUE TITLE
Пулемет-Дробовик

### ISSUE THREAD

**Issue by VorDaz1** [salwador/MTA-DayZ-Ultimate#217]
Баг, позволяющий заряжать в оружие с россыпными патронами до 128 пуль

Для этого нам нужно взять к примеру Протекту и не заряжая ее(обязательно нужны доп патроны) свапать оружие и одновременно бить кулак до того момента пока оружие не сделает выстрел без заряженного магазина

**Последствия.**
Последствия: юз для пвп и делавшие дробовики некой 'имбой'

**Подтверждение**
https://youtu.be/i8fKv34_gsA

**Comment by salwador** [comment]
🤒
