### ISSUE TITLE
Баг анимации персонажа 

### ISSUE THREAD

**Issue by M4RS1** [salwador/MTA-DayZ-Ultimate#218]
**Описание бага.**
Баг анимации благодаря котрому персонаж может резко сесть, а потом встать.

**Воспроизведение.**
В определенный тайминг необходимо ударить и прожать анимацию "сесть" 
(лкм + б)
**Последствия.**
Во время этого бага персонаж не будет получать урон от оружия. 
**Подтверждение**
https://www.youtube.com/watch?v=h-F7mJYvKY0

**Comment by salwador** [comment]
Нужен пруф со стороны, как по такому кенту стреляют и он не получает урона.
То что анимацию перебивает действие - ничего удивительного нет, вряд ли можно считать за баг.

**Comment by M4RS1** [comment]
Вот более весомые доказательства :https://youtu.be/0dTiOYyt-DQ
