### ISSUE TITLE
Прорисовка рюкзака

### ISSUE THREAD

**Issue by denisFo** [salwador/MTA-DayZ-Ultimate#22]
Как видно на скриншотах при отдалении от тела, рюкзак на 8 слотов отображается, в то время как на соседнем трупе надет рюкзак на 24 и он пропадает.Заметил данное явление только на рюкзаке на 24. Было бы отлично, если б вы исправили данный баг с прорисовывающимся рюкзаком на расстоянии(часто бывает такое, что сразу видишь рюкзак игрока, а потом уже, подбежав, увидишь и саму текстуру человека). Так же это распространяется на бронижилеты(они все прорисовываются на большом расстоянии)
Скриншот: http://imgur.com/a/zJPSR

**Comment by salwador** [comment]
Fixed 1.2.30+
