### ISSUE TITLE
Animation Bug

### ISSUE THREAD

**Issue by Emre-31** [salwador/MTA-DayZ-Ultimate#225]
Animation bug

To make this bug, you need to punch and press the sit button quickly (it works on dead bodies too) I show it in the video. You cant see it, but other players will see you sitting and running.

https://www.youtube.com/watch?v=LavapdZsQJ0

**Comment by Emre-31** [comment]
> https://www.youtube.com/watch?v=LavapdZsQJ0



> Animation bug
> 
> To make this bug, you need to punch and press the sit button quickly (it works on dead bodies too) I show it in the video. You cant see it, but other players will see you sitting and running.

> https://www.youtube.com/watch?v=LavapdZsQJ0

**Comment by salwador** [comment]
Already fixed in patch 1.4.9.1.
