### ISSUE TITLE
Баг с хеликрашем в СФ

### ISSUE THREAD

**Issue by Xamele0n41k** [salwador/MTA-DayZ-Ultimate#227]
**Описание бага.**
Скорее не баг, а недоработка

**Воспроизведение.**
найти хели краш БТРа в СФ который стоит на дороге
начать его лутать
он исчезнет (не всегда)
или просто не даёт его лутать (тоже не всегда)

**Последствия.**
Не даёт возможность залутать хеликраш

**Подтверждение**
https://youtu.be/pYJcv5aBNN0

**Дополнительная информация**
Даже не знаю как её воспроизвести, раз на раз не приходится, но на видео видно

**Comment by salwador** [comment]
Забавно, просто попал в тайминг респауна.
