### ISSUE TITLE
Animation bug 

### ISSUE THREAD

**Issue by PredatorNemesi** [salwador/MTA-DayZ-Ultimate#228]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**Additional context**

**Comment by PredatorNemesi** [comment]
the bug consists of running with the animation of sitting down "," In the video you can see SASPredator # 1 (aldo) "old player who was admin and banned all players" and SASCamilo (brother of the player mentioned above)
 
In the video you can see that they hit him in the head and tell him about the bug in the chest (the bug makes the other see you with the animation when you are really stopped, so in the camera of the recording you can see that hits him on the head but he's really standing so he hits him on the chest) [https://www.youtube.com/watch?v=x3371gssn3U](url) in this video if you put it in slow motion you can see how the player "Camilo" moves while sitting.
Now the excuse will be that it is not the one who put his name, That video was the date 09/30/21 at 06:06 gtm + 3 on the ship of that date you can check the logs to know exactly who the player is### Camilo Animation bug (SERVER MARENGO)

**Comment by salwador** [comment]
Already fixed in patch 1.4.9.1.

**Comment by PredatorNemesi** [comment]
Ok thanks but i taked. Ban perma for it u can unban me pls?  My serial:
8AA407F9AC487ED434110E700B22DB02
