### ISSUE TITLE
Исправление повреждений зомби и попадание в воду

### ISSUE THREAD

**Issue by denisFo** [salwador/MTA-DayZ-Ultimate#24]
С зомби, как и с дождем, тоже проблема. Они тут тоже имеют сверхсилу. При падении с любого здания они остаются живы и здоровы. Сделайте так, что бы они получали урон от падения, или просто умирали при нем. Так же хотелось бы предложить смерть зомби от попадания в воду. Где видано, что зомби умеют плавать? Они ходить то еле еле могут.

**Comment by salwador** [comment]
Смерть зомби от падений будет добавлена в следующих версиях
