### ISSUE TITLE
Усталость при забитом рюкзаке на 8 слотов

### ISSUE THREAD

**Issue by denisFo** [salwador/MTA-DayZ-Ultimate#26]
Есть такая особенность, очень и очень тупая, как мне кажется. Все знают, что при забитом рюкзаке наступает усталось. При загруженом рюкзаке на 32-44 вопросов нету, но вот когда ты устаешь при загруженом рюкзаке на 8 это уже что то с чем то. т.е. я могу носить рюкзак на 44 и забив его на 30 слотов я уставать не буду, а вот при забитом рюкзаке на 8 я будто кирпичи ношу. Исправьте.

**Comment by salwador** [comment]
Посмотрим.

**Comment by salwador** [comment]
Теперь при надетом рюкзаке менее 16 слотов - усталость будет брать значение максимального переносимого веса в 16 слотов. Далее по возрастанию, в зависимости от надетого рюкзака.
Появится в версии 1.2.30+
