### ISSUE TITLE
Баг со сменой оружия

### ISSUE THREAD

**Issue by denisFo** [salwador/MTA-DayZ-Ultimate#27]
Бывают такие случаи, что при перестрелки тебе нужно быстро сменить одно оружие на другое(К примеру ЦЗ на М16). Но в то же время тебе надо сразу же после смены оружия начать стрелять.. и тут начинается самое интересное. Ты просто не можешь выстрелить, будто что то блокирует. Надо ждать немного, что бы можно было стрелять, но тебя могут уже убить. Как то так, думаю меня поймут.

**Comment by salwador** [comment]
Это КД по смене оружия, так и задумано. Та самая задержка после использования предмета (крутящийся круг вокруг курсора).
