### ISSUE TITLE
Урон от кулака.

### ISSUE THREAD

**Issue by denisFo** [salwador/MTA-DayZ-Ultimate#29]
Я конечно все понимаю, но если я бью морду какому то игроку или даже давлю ногами и он не получает ну никакого урона - то это пиздец как не правильно. Очень не хватает рукопашного урона.

**Comment by salwador** [comment]
Хочешь чтоб кепки на респауне друг другу ебальники били?
Это не будет иметь смысла, поскольку никого с кулака не убьёшь, ибо урон будет порядка 70-120.

**Comment by denisFo** [comment]
Бывают такие моменты, когда ложишь человека , а добить нечем. Потом он встаёт с 200 крови и убивает тебя. Есть смысл
