### ISSUE TITLE
Баг со слотами. 

### ISSUE THREAD

**Issue by Jakob227** [salwador/MTA-DayZ-Ultimate#30]
Суть бага в том, что если забить инвентарь чем-либо, потом юзнуть оружие, потом снова забить и убрать оружие - то в инвентаре будет забито слотов больше, чем максимум. Баг конечнобесполезен, но все-же это баг. На видео думаю будет все понятнее https://youtu.be/3jgW-Al-BPY

**Comment by salwador** [comment]
А это и не баг. Ты убираешь оружие в рюкзак, получаешь перегруз. Следовательно - стамина кончается быстрее.
