### ISSUE TITLE
ENG: New cars? Reason in description

### ISSUE THREAD

**Issue by naucaa** [salwador/MTA-DayZ-Ultimate#31]
Why servers need new cars? At the moment it looks like good dayz with shit cars, only good car is white ford (f150) and red ford and sanchez, but thees cars still have some issues...

**Ford F150**
- bumpy on surface

**Red Ford**
- when smth hit its ok, but when hit harder than normal u will need painkiller, morphine, medic (very hard to drive roads with moded crashed cars on it)

**Rusty cars**
-Totaaly shit
-bumpy
-they might flip over your car when u drive fast on road edges/borders (especially in city)
-driveability is 0

**Chevrolet ss**
-good, but too young for Dayz. its not oldschool drift server its dayz, zombie acopalipse.. :/

**Volvo**
-please UNINSTAL that crap, every turn is on roof...

**Chevrolet suburban**
- goood, but still if u hit smth, need morphine and painkiller

**White cadilliac**
- mostly... no one use it.. 

**Sanchez**
-if u touch with your front wheel something at Dayz human running speed it will not be green as it was before u hit the wall, it would be orange or red. It means, sanchez can easely destroi him sellf, if u fall of bike for example..

**URAL**
-SELF DESTROYING CAR

**white GMC VAN**
-In russian: белый холодильник no one needed.

# How to fix it?!

We need cars that match Dayz playstile.

![image](https://user-images.githubusercontent.com/31653649/30512395-54779a6e-9af7-11e7-88b8-e1c1be80e16b.png)

![image](https://cs2.gtavicecity.ru/screenshots/9a0d4/2016-02/original/c7ad111f9bb74482198e4180f19d7026c54ad228/321585-gta-sa-2016-02-19-13-09-46-47.jpg)

Link : https://www.gtavicecity.ru/gta-san-andreas/cars/74551-volkswagen-caddy-military-vehicle.html

![image](https://cs1.gtavicecity.ru/screenshots/9a0d4/2017-03/large-fit/d8560eb036c54c79feec8f155ece72d681f746b6/390654-enb-2017-03-17-07-16-44-74.jpg)
![image](https://cs1.gtavicecity.ru/screenshots/9a0d4/2017-03/large-fit/112ba9c9dc8f2a4035831a9164e67a6775ab2bdd/390656-enb-2017-03-17-07-17-00-09.jpg)

Link: https://www.gtavicecity.ru/gta-san-andreas/cars/85507-kamaz-6350.html

![image](https://user-images.githubusercontent.com/31653649/30512538-66973fc6-9afa-11e7-9c16-2ba1ea2ef5e7.png)

![image](https://user-images.githubusercontent.com/31653649/30512541-732072f8-9afa-11e7-8d7e-d8ae3405baf1.png)
Link: https://www.gtavicecity.ru/gta-san-andreas/cars/92536-volkswagen-golf-mk2-country.html

![image](https://user-images.githubusercontent.com/31653649/30512560-e023173e-9afa-11e7-9106-9848b055eb3a.png)

![image](https://user-images.githubusercontent.com/31653649/30512563-e831ad1e-9afa-11e7-9d1f-02752f6c5eb5.png)
Link: https://www.gtavicecity.ru/gta-san-andreas/cars/91976-toyota-land-cruiser-200.html

![image](https://user-images.githubusercontent.com/31653649/30512607-28941238-9afc-11e7-903e-c134846db59d.png)

![image](https://user-images.githubusercontent.com/31653649/30512629-99b1b952-9afc-11e7-91f9-a5ee0d93a635.png)

Link: https://www.gtavicecity.ru/gta-san-andreas/cars/94451-tatra-613-rusty.html

Cars like this would make dayz more realistic. and with fresh look :) 💯  👍 :1st_place_medal:

**Comment by salwador** [comment]
No bug, and useless issue. If we will wanna add new vehicles - we can make it without you.

**Comment by naucaa** [comment]
uless isue its for u, because u are too layzy to do it, and u dont play like most players about 5-8 hours. and when u need to drive shit cars which is full of bugs and glitches. selfish admin

**Comment by salwador** [comment]
blah blah blah
you just a crying girl who wanna new cars
