### ISSUE TITLE
Баг с починкой.

### ISSUE THREAD

**Issue by Jakob227** [salwador/MTA-DayZ-Ultimate#33]
При починке машины меня убили, когда я возродился - я продолжал ее чинить.
![mta-screen_2017-09-18_19-06-34](https://user-images.githubusercontent.com/31757523/30552328-400e9aea-9ca6-11e7-98b9-09359394057e.png)
![mta-screen_2017-09-18_19-06-47](https://user-images.githubusercontent.com/31757523/30552327-400b2090-9ca6-11e7-9789-9124b024c5fd.png)

**Comment by salwador** [comment]
Fix in 1.2.30+
