### ISSUE TITLE
Многократное выполнение действия при нажатии кнопки.

### ISSUE THREAD

**Issue by 666ybuica666** [salwador/MTA-DayZ-Ultimate#35]
После 2х рестартов появился баг, иногда невозможно выбрать, что конкретно ремонтировать. Нажимая на ремонт , автоматически ремонтируется первая деталь из списка. Релог и смена наборов инструментов, а так-же переустановкаклиента не спасают. Позже добавлю видос с багом.
Проблема наблюдается не только у меня, как минимум 10 человек наблюдают это у себя в игре.
Весьма дискомфортная вещь, ибо когда требуется ремонт лишь корпуса(пробитие колёс например), приходится чинить всё подряд, пока не дойдет до самого, ремонта корпуса.

**Comment by 666ybuica666** [comment]
Так-же , поошу заметить, что игра как будто считает одно нажатие на "Е"(кнопка действия), за 2-50 нажатий,что прекрасно наблюдается при попытке нажать на (осмотреть труп,дадабы узнать время смерти), нажимая на данную позицию, игра выдает от двух вплоть до пятидесяти строк , с информацией о смерти трупа. Строки повторяются. Скриншот загружу позже.

**Comment by salwador** [comment]
Опа, а вот это уже годный баг. Не то что нытьё а-ля "не даёт выбрать запчасть".
Теперь есть догадки в какую сторону копать, хотя странно что я его ни разу не поймал.

**Comment by salwador** [comment]
Fixed in soon biulds

**Comment by salwador** [comment]
¯\_(ツ)_/¯

**Comment by salwador** [comment]
Модераторы, тестеры и игроки сообщают о том - что баг более не встречался.
Значит его исправление выполнено.
