### ISSUE TITLE
Баг с добычей мяса их животных.

### ISSUE THREAD

**Issue by ZhekaRDS** [salwador/MTA-DayZ-Ultimate#36]
При себе имею охотничий нож, но мясо из трупов животных нельзя добыть. Не появляется раздел "Добыть мясо"
![utxryy_urrg](https://user-images.githubusercontent.com/31547029/30712216-7746b042-9f35-11e7-9632-1cfefb53290c.jpg)

**Comment by salwador** [comment]
Лол, так ведь исправлено было.
