### ISSUE TITLE
непонятки с оружием и патронами

### ISSUE THREAD

**Issue by KaSpEr04ek** [salwador/MTA-DayZ-Ultimate#37]
В общем баг, или не баг, сам точно не знаю, связан с тем, что когда экипируешь оружие в инвентаре, оно *пропадает*, и перестаёт занимать место в инвентаре, а с патронами такого не происходит, Т.Е. когда заряжаешь оружие, обойма или коробка патронов не *пропадает* из инвентаря и продолжает занимать место в инвентаре, ладно там штурмовые винтовки, они всего 1 слот занимают, но когда их несколько обойм или вообще коробка на пулемёт, то они занимают много места, и порой из-за этого возникают трудности с переносом лута, оссобенно на дропах, хотелось бы видеть на сервере чтобы когда заряжаешь оружие, обоймы *пропадали* и не занимали место, а то такое ощущение складывается, что я что то зарядил, а по факту нет, т.к. обойма лежит в инвентаре.

**Comment by KaSpEr04ek** [comment]
И продолжает занимать место в рюкзаке

**Comment by salwador** [comment]
Патроны не экипируются, и не должны. Поэтому они и занимают место.
Закрывать не стану, может когда-то и решим это изменить.
