### ISSUE TITLE
Баг с выбором оружия

### ISSUE THREAD

**Issue by SlING228** [salwador/MTA-DayZ-Ultimate#4]
Когда выхожу из ТС, оружие не берётся или не переключается. Это происходит очень часто.

**Comment by salwador** [comment]
Никогда не замечал такого. Какое-то подтверждение будет?

**Comment by ARMA-Servera-Brown** [comment]
salwador я тоже с такой фигней встречался неоднократно и из-за нее сливался потому что не мог выбрать оружие

**Comment by ARMA-Servera-Brown** [comment]
сальвадор вот видео там нарезано те моменты когда оружие не меняется, сам попробуй на сервере посадиться в машину когда у тебя экипировано 2 оружия и повылазить с нее и покрутить на колесико или на кнопки q или e что бы сменить оружие. 
Видео: https://youtu.be/FEn6eGiCDRM

**Comment by salwador** [comment]
Fixed in 1.2.27+
