### ISSUE TITLE
Баг с заражением

### ISSUE THREAD

**Issue by KaSpEr04ek** [salwador/MTA-DayZ-Ultimate#40]
Заключается он в том, что когда у тебя заражение, и доходит до 3 стадии заражения, ничегон е изменяется, но когда падаешь в отключку, должен появится антирелог, он не появляется, и после того как встал из отключки, кровь перестаёт убавляться, и бывает даже такое, что когда выходишь из сети с заражением, и потом заходишщь, ты умираешь, ну точнее появляешься на респе *Кепкой*

**Comment by salwador** [comment]
> у тебя заражение, и доходит до 3 стадии заражения, ничего не изменяется, но когда падаешь в отключку, должен появится антирелог, он не появляется

Сегодня падал - всё появлялось. Возможность бага не исключена. 
Найдёшь причину - будем благодарны.

**Comment by KaSpEr04ek** [comment]
причину я не найду, ( Мне так кажется ) но что нибуть постараюсь накопать, чтобы было больше информации
