### ISSUE TITLE
Баг с зомби

### ISSUE THREAD

**Issue by KaSpEr04ek** [salwador/MTA-DayZ-Ultimate#43]
Заключается он в том, что когда наступает ночь на сервере Brown все знаю что зомби начинают бегать, причём моментально, даже те которые заспавнились до 00:00, а вот когда наступает утро 06:00 почему то зомби так же резко не перестают бегать, как ночью начинают, надеюсь ход моих мыслей до вас дошёл.

**Comment by salwador** [comment]
Не баг.
