### ISSUE TITLE
Падение под текстуры

### ISSUE THREAD

**Issue by KaSpEr04ek** [salwador/MTA-DayZ-Ultimate#44]
Незнаю с чем связано, но когда у тебя экипирован FN fal и ты бегаешьс ним, и бывает резко переключаешь оружие, бывает так что при переключении оружия у тебя камера быстро к скину приближается, а потом отдаляется в исходное положение, а бывает и вовсе ты из-за этого падаешь под текстуры, сам лично уже устал падать из-за этого

**Comment by KaSpEr04ek** [comment]
Ошибочка, с любым оружием падаю как минимум я под текстуры, особенно часто если стою у машины после починки или у палатки, и как выхожу из неё, и оружие убираю или достаю, то тогда чаще всего падаю под текстуры

**Comment by salwador** [comment]
Исправлено в следующих билдах, как обычно.
Закрою после тестирования.

**Comment by salwador** [comment]
Модераторы, тестеры и игроки сообщают о том - что баг более не встречался.
Значит его исправление выполнено.
