### ISSUE TITLE
Невозможно выбрать что чинить!

### ISSUE THREAD

**Issue by TypicalRussian** [salwador/MTA-DayZ-Ultimate#45]
Сегодня проебал лут из-за этого. Уезжать начал выбили бак, спрятался в место, начал чинить по порядку, бак чинится в последнюю очередь не считая корпуса. Пока чинил подошел кепка с СМ и убил. Почините это пожалуйста ибо не у меня 1 такая поебень.

**Comment by salwador** [comment]
Хватит дублировать баги. Закрыл уже одно из твоих сообщений, оставив ссылку на дубль. Ты не успокоился и открыл снова, с тем же багом... =/
https://github.com/salwador/MTA-DayZ-Ultimate/issues/35

**Comment by TypicalRussian** [comment]
Так а фиксить будете?

**Comment by salwador** [comment]
Когда кто-то найдёт причину - пофиксим.
У меня таких проблем нет.
