### ISSUE TITLE
[Bug] с KILL листом на сервере Lime

### ISSUE THREAD

**Issue by MegaAidar** [salwador/MTA-DayZ-Ultimate#46]
Сначало в двух словах, а потом подробнее. После бага килл лист(т.е (ник) погиб) переносится на середину не изменяя шрифт и размер. Правее середины.
===========Описание Бага===============
Для начало нужно забить себе фулловый инвентарь, в моём случае это рюкзак на 20 слотов.
После чего, подобрать с земли  ЧУЖИЕ болты от арбалета. Нажимать на "Е" 2-3 раза. Чат профлуживается и переносится наверх, затем остаётся в этом положении до тех пор, пока не релогнишься. Скрины,думаю, не обязательны.

by MegaAidar[Lime]

**Comment by salwador** [comment]
Fixed in soon biulds
