### ISSUE TITLE
[Bug] Труп.

### ISSUE THREAD

**Issue by MegaAidar** [salwador/MTA-DayZ-Ultimate#47]
Кратко говоря, а потом подробно. После бага, мёртвое тело исчезает.
============Описание бага===========
После убийства мною персонажа [1 из 5] по моей статистике просто исчезает, он умирает , но трупа на месте убийства нет, даже в ближайших 20 м. не видно. Персонаж которого убили не вышел из игры, в килл лист было написано что он погиб, но тела нет.

by MegaAidar[Lime]

**Comment by salwador** [comment]
> После бага, мёртвое тело исчезает.

После какого бага? Где информация о баге? Я вижу только то - что ты мог сливать недавно заспавненных кепок, от которых не остаётся труп.

**Comment by salwador** [comment]
За неимением информации - будет закрыто.
