### ISSUE TITLE
[Bug] Ночное видение

### ISSUE THREAD

**Issue by MegaAidar** [salwador/MTA-DayZ-Ultimate#48]
Кратко говоря, а потом подробно. После бага, ночное видение выключается.
============Описание бага===========
После того как вы оденете маскировку с ВКЛЮЧЕННЫМ ночным видением, оно выключается, приходится заново включать. 

by MegaAidar[Lime]

**Comment by KaSpEr04ek** [comment]
ну да, так и должно быть, сам по логике вещей по суди, ты сидишь в  кепке, и решил переодеться, чё кепку снимать не будешь ? так через неё переоденешься ?
