### ISSUE TITLE
[Bug] Точка Доступа

### ISSUE THREAD

**Issue by MegaAidar** [salwador/MTA-DayZ-Ultimate#49]
Кратко говоря, а потом подробно. После бага, точка доступа исчезает, а связи остаётся
============Описание бага===========
После того как вы поставили точку доступа и установили связь сверните его, в инвентаре его нет, как и на месте на котором он был установлен, но при этом связь остаётся
by MegaAidar[Lime]

**Comment by salwador** [comment]
Fixed in soon builds
