### ISSUE TITLE
[Bug] Сбив анимаций

### ISSUE THREAD

**Issue by MegaAidar** [salwador/MTA-DayZ-Ultimate#50]
Кратко говоря, а потом подробно. После бага, можно сбить любую анимацию в ТС.
============Описание бага===========
Сядьте в машину и например используйте медикаменты, он присядет в мотоцикле, но управлять ей можно. Т.е. управлению это никак не мешает. Любая анимация и любой ТС
by MegaAidar[Lime]

**Comment by salwador** [comment]
Не баг.
