### ISSUE TITLE
[Bug] Исчезание Мусора

### ISSUE THREAD

**Issue by MegaAidar** [salwador/MTA-DayZ-Ultimate#51]
Кратко говоря, а потом подробно. После бага, мусор просто исчезает.
============Описание бага===========
Запрыгните на движущийся авто и к примеру съешьте банку сардин, после того как он их съест он выкинет на землю, но они исчезают при падении. Так с любыми продуктами после которых остаётся мусор.
by MegaAidar[Lime]

**Comment by salwador** [comment]
Мусор не исчезает, а остаётся на позиции "под ногами". И останется висеть воздухе - когда машина отъедет. Это не баг.
