### ISSUE TITLE
[Bug] Снаряжение

### ISSUE THREAD

**Issue by MegaAidar** [salwador/MTA-DayZ-Ultimate#52]
Кратко говоря, а потом подробно. После бага, персонаж не снимая каску одевают еще одну.
============Описание бага===========
персонаж не снимая военный шлем может одеть еще один, что противоречит бронежилету, бронежилет нужно снять и одеть, а с военным шлемом только одеть. 
by MegaAidar[Lime]

**Comment by salwador** [comment]
Головные уборы заменяются, поскольку от них ничего не зависит.
У жилетов же есть своя ёмкость.

В каком месте это вообще баг?
