### ISSUE TITLE
Текстурный баг

### ISSUE THREAD

**Issue by CrabbyAdei71** [salwador/MTA-DayZ-Ultimate#54]
https://user-images.githubusercontent.com/31574768/31717746-d4878ac0-b415-11e7-8d60-86bf5473baa8.png
https://user-images.githubusercontent.com/31574768/31717747-d4a61800-b415-11e7-9d18-2ab068e6d151.png
https://user-images.githubusercontent.com/31574768/31717749-d4c47dea-b415-11e7-9f8d-b8abd45bdeef.png

**Comment by salwador** [comment]
fixed in soon builds
