### ISSUE TITLE
Баг с БТРом

### ISSUE THREAD

**Issue by KaSpEr04ek** [salwador/MTA-DayZ-Ultimate#55]
В общем баг заключается в том что, БТР самый защищённый транспорт на сервере, тогда у меня возникает вопрос, почему при малейшем столкновении у меня очень много отнимается крови, я что в консервной банке катаюсь ? или всё таки в БТРе, и да, если удариться со всей силой в стену на БТРе то я  вовсе вылетаю из БТРа и ложусь в отключку, вопрос, как ? почему я не ложусьв отключку в БТРе ? места мало ? или я всё таки в консервной банке катаюсь ?

**Comment by salwador** [comment]
А кто тебе сказал что на БТР ты можешь врезаться куда попало, только потому что у него хорошая броня?
