### ISSUE TITLE
АЕК-971GL

### ISSUE THREAD

**Issue by KaSpEr04ek** [salwador/MTA-DayZ-Ultimate#56]
на сколько я помню, в хеликрашах его не найти, да и на военках тоже, но тут такая загвостка, играю на Brown и беру почти каждый дроп, но АЕК я уже давно не встречал в дропах, почему он пропал из выпадения в дропах ? как минимум уже 2 месяца он не падает

**Comment by salwador** [comment]
Его нет, и никогда не было в дропах. Это исключительно редкий военный лут.
