### ISSUE TITLE
Lights of vehicle and turning on the "watches". Появление часов при включении фар, либо при нажатии  "L".

### ISSUE THREAD

**Issue by 666ybuica666** [salwador/MTA-DayZ-Ultimate#57]
When turning on the lights of a vehicle or even without vehichle , while pressing "L" key , the watches just turn on for a second , and close in next 1-2 seconds.
________________________________________________________________________________________________________________

При включении фар автомобиля, или же просто, при нажатии "L" ("Д" рус.), происходит секундное появление часов в HUD`е  и их мнговенное исчезание.
_______________________________________________________________________________________________________________

Видео : https://drive.google.com/open?id=0B8wX_R8zNHMWY3YtVE9iNktlOFE

**Comment by salwador** [comment]
Часы включаются потому что на L, а компас на B.
