### ISSUE TITLE
bag helli under map

### ISSUE THREAD

**Issue by naucaa** [salwador/MTA-DayZ-Ultimate#6]
hello. first of all, i would like to say this is one of my favorite dayz server. Second, there is bug where u can use heli to get under fucking map. After looooong, loooong, looong serching of tents i couldnt understand where they are hided... i looked for stock places, i looked better places sometimes i found smth but it was usefull.  then i found way to get under map and noticed that there are FEW tents under map on tunels, some map bugs etc, there was many accespoints under of it, and that was the moment i knew the truth why im unlucky always. There are some morons before me, who used heli to get under map to loot tents and then put in bases. Thats why some players in lime, marengo, green are super looted and most of them have base with heli. They easy fly trought map, find loot then hide in bases and use in pvp. thats not fair!

And i belive this is one big issue in al BS Ultimate servers. About year ago i played very good there, got no base, got 7 tents well hiden which stayed for about 3-4 months  and then in one day they all was gone. I remember i played and even i then when i knew that bug, i still could find tents or as i call - tent city's with atleast 3 or 5 tents in same place. thats mean i didnt needed get under map. :/ 
But if u got robbed every time u lost intrest of server. for example about month ago i got tent which i earned in pvp good, about 11 mags for each stock weapon - m4, AK etc, and i got robbed after 3-4 days. cuz someone was under map and easy saw them.

i can say where is bug, i dont care if i get ban or not, but make thi server great again, make to come people back, make them to make tents more. write me in eamil an i wil show screnshots for salwador **isaisltd@gmail.com**

**Comment by salwador** [comment]
@naucaa can contact with me beststudiomta@gmail.com, if not wanna public info.

**Comment by salwador** [comment]
Fixed in 1.2.27+
