### ISSUE TITLE
баг с перемещением

### ISSUE THREAD

**Issue by KaSpEr04ek** [salwador/MTA-DayZ-Ultimate#63]
Даже не знаю как назвать, багом или нет, ну в общем суть такова, у меня к примеру 30 кусков мяса в инвентаре, почему я не могу их сразу закинуть все в палатку кучей, а не складывать их аккуратненько в палатку, и да, почему я не могу поесть из палатки, почему же мне нужно сначало перемещать в инвентарь, а потом уже употреблять пищу, почему я не могу взят и сразу съесть, без лишних телодвижений, которые заключаются в том что сначала еду или воду в инвентарь, а потом уже употреблять её, почему я не могу её *взять в руки* и с разу употребить ?

**Comment by salwador** [comment]
Механика такая заложена в коде. И спустя 4 года менять это никто не будет.
А по быстрому перемещению - такое дерьмо искать стоит точно не у нас.
