### ISSUE TITLE
патроны к ЦЗ

### ISSUE THREAD

**Issue by KaSpEr04ek** [salwador/MTA-DayZ-Ultimate#64]
Почему нельзя к примеру в ту же самую палатку положить не сразу все патроны к ЦЗ, а к примеру половину, ну допустим у меня 8 патронов, 1 заряжен, 7 в инвентаре, я посчитал что мне нужно оставить к примеру 3 Пт, и положить, 4, почему я не могу так сделать, в общем разделить лут почему нельзя ?

**Comment by KaSpEr04ek** [comment]
И да, к примеру если в санчез влезает 8 мест, и допустим в санче занять 7.8 то туда можно спокойно положить 5 патронов к ЦЗ, которые занимают 1 место

**Comment by salwador** [comment]
Хватит создавать тупые темы, с тупыми именами. Все знают что патроны стакаются по 5 шт.
И да, тебе стоит научиться писать заголовки с большой буквы.
