### ISSUE TITLE
Некорректная защита от пуль

### ISSUE THREAD

**Issue by KaSpEr04ek** [salwador/MTA-DayZ-Ultimate#66]
В общем баг заключается в том, что если стрелять в голову к примеру с SA-58P то дамаг проходит только на 2450 крови, в замен своих 3182, и если стрелять с любого другого ствола, нося каску HBM-O, то дамаг будет только расти, ну тот который заблокируется, не кажется это странным, что чем мощнее оружие, тем сильнее защищает от пуль ? Лучше сделайте так, чтобы к примеру бронежилеты не по процентам, а по определённому порогу защищали от пуль

**Comment by salwador** [comment]
> Защита по процентам
> Не нравится то что она по процентам
> Пишет "некорректная"

И да, это наитупейшая идея, а-ля "давайте убьём баланс нахуй".
