### ISSUE TITLE
Отсутствуют полезные места на карте

### ISSUE THREAD

**Issue by KaSpEr04ek** [salwador/MTA-DayZ-Ultimate#68]
Косяк заключается в том, что когда ты открываешь карту, там есть debug монитор в низу, и там написано, что если нажать на клавишу num 9 то будут отображаться полезные места, но при нажатии на эту клавишу вообще ничего не происходит, было бы неплохо чтобы всё таки эти полезные места появились, а ещё лучше, если бы сам игрок для себя мог сам рисовать эти полезные места

**Comment by salwador** [comment]
Будь добр, научись нормальные названия делать, а не от балды.
И да, полезные места так и не добавили.

**Comment by salwador** [comment]
added in 1.3
