### ISSUE TITLE
Баг с патронами

### ISSUE THREAD

**Issue by KaSpEr04ek** [salwador/MTA-DayZ-Ultimate#69]
Есть такая вещь, в общем она заключается в следующем, мне надоело играть, и я решил выйти с серва, в обойме заряжена полная обойма, в инвентаре ещё 1 есть, на ( к примеру ) 3 патрона, при новом заходе на сервер, почему то именно эта обойма с меньшим количеством патрон в ней всегда оказывается заряжена, и бывает так, что ты заходишь, а перед тобой человек, и ты его не убиваешь лишь из-за того, что у тебя при заходе на сервер стала обойма не на ( к примеру ) 35 патрон, а на 3 патрона

**Comment by salwador** [comment]
Не баг, а используется рандомный магазин.
