### ISSUE TITLE
AirDrop

### ISSUE THREAD

**Issue by KaSpEr04ek** [salwador/MTA-DayZ-Ultimate#70]
даже не знаю, баг или так запланирвано, в общем, если на сервере 10 человек, то дропы запускаются и их количество составляет 3 штуки, если 20 человек, то 5 дропов, если 25 человек, то 6 дропов, а вот если 15 человек, то дропов всё равно 3, как то странно, что 4 дропов вовсе не бывает

**Comment by salwador** [comment]
Ничего странного, так и задумано.
