### ISSUE TITLE
Банка макарон

### ISSUE THREAD

**Issue by KaSpEr04ek** [salwador/MTA-DayZ-Ultimate#73]
Если у тебя еды вообще нет, то даже если ты съешь пол банки макарон, у тебя восстановится почти вся *Полоска* еды, как то не правильно, ведь даже от мяса не всё восстанавливается

**Comment by salwador** [comment]
Эффект рандомный. Например консервы от 40 до 60, а мясо от 50 до 80. (Цифры не точные)
А индикатор на экране не показывает точное количество сытости, поэтому в сочетании - это таким и кажется.
