### ISSUE TITLE
Ключи

### ISSUE THREAD

**Issue by TypicalRussian** [salwador/MTA-DayZ-Ultimate#75]
Представте себя в игре. В один обычный день проснувшись с утра, вы отправляетесь по своим делам, попутно закрыв дверь своего дома. Вы имеете с собой ключ, а то и не один. Один от машины, второй от квартиры, третий от гаража и т.д. И тут вдруг хуяк и аппокалипсис. Вы стали зомби. Гуляете по улицам в поисках человеков. И тут изза угла вылетает кепка на велосипеде, достает глок и убив тебя, начинает искать лут в твоих потрохах и находит ключ. Радостно сев на велосипед, кепка едет мочить зомби дальше в поисках ключей, чтобы после отправится на зону и открыв контейнеры - залутатся. Идеально не правда ли? Только вот почему зайдя на любой сервер проекта Ultimate, и убив десяток зомби, я нахожу от силы 1 ключ? Нехорошо... Надо бы исправить.

**Comment by salwador** [comment]
Нечего тут исправлять.

**Comment by TypicalRussian** [comment]
А где тогда их искать? Сделай хотябы чтоб ключи были в каждом 3 зомби, А то релут часто постоянно закрытые контейнеры, а ключи хрен найдешь

**Comment by salwador** [comment]
Заебись, ключи к военному луту в каждом третьем зомби. Головой думаем вообще?

**Comment by TypicalRussian** [comment]
А тогда какого хрена эти ключи делают у колхозников?

**Comment by salwador** [comment]
А где им ещё быть? Лол, в военном луте? Хуйню не пори.
Они там - где и должны быть. Если тебе их не хватает - это только твои проблемы. И предлагать подобный бред не надо.
