### ISSUE TITLE
Неполадки с GPS

### ISSUE THREAD

**Issue by KaSpEr04ek** [salwador/MTA-DayZ-Ultimate#76]
Это сервер игры, постаппокалипсиса, Я понимаю что частота GPS вмерцает, ну там точка доступа барахлит, да и в мире не всё спокойно, чтобы она работала, ну ладно, то что мерцает GPS фигня, но блин, почему когда я навожусь на человека мне показывает его ник, я что блин всех знаю в ицо, даже новых игроков, откуда, да если ещё со спины на него смотреть, я что всех ещё и по жопе могу различать ? в общем было бы неплохо вообще убрать ники игроков, и оставить только тех, которые к примеру на твоей частоте сидят, или что то типо команды создавать, чтобы видить своих и за стеной, ну или хотя бы чтобы их было видно в чистом поле, а всех чужих не показывать ники, так и атмосферности добаить как минимум на сервер Brown, потому что там хардкор

**Comment by salwador** [comment]
Заебал писать всю тупую хуйню, которая тебе приходит в голову.

**Comment by KaSpEr04ek** [comment]
Почему именно приходит, ты хоть сам видишь чё на серверах происходит ? или так по слухам ориентируешься ? зайди хоть разок, поиграй, и сам увидешь что блять пропадает точка зелёная, твоего тиммейта иногда, время от времени, а общая не пропадает, не моргает, только зелёная, и именно на GPS она сука мерцает, иногда кабздец как раздражает и по ошибке из-за того что лагала, мерцала, ты валишь не врага, а своего, потому что оссобенно на ПВП и на дропах, ты не смотришь на ник. а фастом глянул на GPS и примерно заметил где находится тиммейт, и всё, остальныхв валишь, а бывает пропадает и нихера не видно, ыт паникуешь и начинаешь валить всё что движется

**Comment by salwador** [comment]
> Неполадки с GPS
> Было бы неплохо вообще убрать ники игроков
> Атмосферности добавить

> Заебал писать всю тупую хуйню, которая тебе приходит в голову
