### ISSUE TITLE
Баги обновления.

### ISSUE THREAD

**Issue by TypicalRussian** [salwador/MTA-DayZ-Ultimate#77]
![mta-screen_2017-12-06_16-28-57](https://user-images.githubusercontent.com/32441003/33664387-82781e74-daa4-11e7-884d-f9db580c8eac.png)
![mta-screen_2017-12-06_16-37-35](https://user-images.githubusercontent.com/32441003/33664389-82b20094-daa4-11e7-92ce-c51f434f28b4.png)
Первые баги. Убитые зомби и люди стоят, И костюм не должен светится в пикв так же как и шлем. Если найду - дополню

**Comment by salwador** [comment]
Скин должен светиться, иначе какой смысл от инфракрасного?
Бага с зомби не вижу. 
![image](https://user-images.githubusercontent.com/12719219/33668206-cc37d022-daea-11e7-8a8a-bfc66bdaace4.png)

**Comment by TypicalRussian** [comment]
Лол, а тогда во 1 почему не просвечивает голова? Во 2 какой тогда смыл от маскхалата? орууу

**Comment by salwador** [comment]
потому что блядь это шлем надет
