### ISSUE TITLE
Одежда

### ISSUE THREAD

**Issue by KaSpEr04ek** [salwador/MTA-DayZ-Ultimate#78]
Незнаю баг или нет, скорее всего так и задумано, в общем, самая обычная одежда даёт нам 6 слотов для лута, а новую которую мы наденим, тоже даёт 6 слотов, дак самая стандартная одежда которая даётся при спавне даёт 6 слотов, в общем по моему мнению чисто лишняя графа добавлена на одежду, ну или можно сделать так, чтобы они как то различались по переносимому луту ( одежда ) или убрать эту графу как и было раньше

**Comment by salwador** [comment]
Beta значит то, что не весь функционал выставлен.
