### ISSUE TITLE
Забаганый камуфляжный скин

### ISSUE THREAD

**Issue by denisFo** [salwador/MTA-DayZ-Ultimate#82]
Довольно сильно бросающаяся в глаза белая "аура" вокруг всего скина.
![mta-screen_2017-12-06_18-06-22](https://user-images.githubusercontent.com/31742115/33781770-e35e230a-dc66-11e7-9ce6-0b12fa3b6cd8.png)

**Comment by salwador** [comment]
Не мы такие, GTA такая. Вокруг травы такая-же херня, если присмотреться
