### ISSUE TITLE
Спавн новых вещей

### ISSUE THREAD

**Issue by denisFo** [salwador/MTA-DayZ-Ultimate#83]
Спавн новых вещей, а именно: скин камуфляжный и шапка к нему спавнятся ну уж очень часто и в многих случаях сразу по 2. Как по мне они должны быть довольно редкими предметами.
![mta-screen_2017-12-06_18-06-33](https://user-images.githubusercontent.com/31742115/33781843-316c2cd6-dc67-11e7-9cc2-c32a21ed4003.png)
![mta-screen_2017-12-06_18-12-17](https://user-images.githubusercontent.com/31742115/33781844-3195c834-dc67-11e7-83b3-c26c6d738246.png)

**Comment by salwador** [comment]
Это мусор, он таким и задумывался. :)

**Comment by denisFo** [comment]
Мусор мусором, но характеристики шлема равны самому толковому шлему. Уменьшите может их?

**Comment by salwador** [comment]
@denisFo, этот "толковый" шлем на PVP серверах тоже встречается часто.
