### ISSUE TITLE
Частота при входе

### ISSUE THREAD

**Issue by denisFo** [salwador/MTA-DayZ-Ultimate#84]
При обновлении заметил такую особенность. Когда заходишь в игру на новый сервер или же после смерти(но это как когда), то частота кидается не рандомно, как это было раньше, а на 0(хотя раньше ее вовсе выбрать нельзя было). И получается так, что зайдя в игру, ты автоматом сидишь на одной частоте с соперниками. Как то так
![mta-screen_2017-12-08_20-54-26](https://user-images.githubusercontent.com/31742115/33781933-94dbcdf8-dc67-11e7-8b4d-bf64e1f76be8.png)

**Comment by salwador** [comment]
fixed
