### ISSUE TITLE
Очень мешает карта.

### ISSUE THREAD

**Issue by denisFo** [salwador/MTA-DayZ-Ultimate#85]
Реально ли сделать так, что бы эту обновленную карту можно было отключать на старую? Мне, как опытному игроку, очень неудобны эти пятна красные и т.п. Думаю не я один такой. Согласен, для новечков это очень крутая помощь.

**Comment by KaSpEr04ek** [comment]
дак ты нажми на num 9 если я не ошибаюсь, и всё, уйдут у тебя эти пятна, что сложно почитать и потестить ?

**Comment by salwador** [comment]
Комментатор выше говорит дело (неужели). Полезные места отключаются нажатием одной кнопки.

**Comment by denisFo** [comment]
Моя невнимательность скорее всего. Но все равно спасибо👌🏿
