### ISSUE TITLE
Оптимизация FPS

### ISSUE THREAD

**Issue by pesotsky** [salwador/MTA-DayZ-Ultimate#88]
При скоплении более 5 игроков в одной локации от привычных 60 остается лишь 15-30 фпс. Играл еще пару лет назад — аналогичная проблема присутствовала. Неужели за несколько лет нельзя было сделать с этим хоть что-нибудь? О каком игровом процессе идет речь, если в нужный момент, на зарубе, ты элементарно не можешь попасть в соперника из-за слайдшоу?

**Comment by TypicalRussian** [comment]
Забудь, никто ничего не будет делать.

**Comment by salwador** [comment]
8 тестеров бегало рядом, 20 трупов с полным обвесом - 60 FPS.

Просадок даже не заметно на моём говёном ноуте, который выше 40 кадров не выдаёт. Много людей - падает на 5-6, и это даже не факт что от людей зависит, поскольку во всех местах на карте производительность может слегка прыгать вверх/вниз.

Пока эта проблема не появится у меня - исправить я её не смогу. Нужно больше информации, поскольку просто так игроки не садят кадры. ._.
