### ISSUE TITLE
Баг с рюкзаком Койот

### ISSUE THREAD

**Issue by NeEvilMuffin** [salwador/MTA-DayZ-Ultimate#89]
Если надевать, допустим, *Зелёный койот*, то в руках у перса будет *Чёрный койот* (во время анимации), и наоборот

1. вот так выглядит баг, когда я надел *Чёрный*:
![-](https://user-images.githubusercontent.com/31744538/34576354-b5716776-f18e-11e7-967c-2d2f69914a56.png)

2. вот так выглядит баг, когда я надел *Зелёный*:
![-](https://user-images.githubusercontent.com/31744538/34576379-d1d864f0-f18e-11e7-98ff-7542146e849f.png)

P.S. С коричневым койотом не пробовал, т.к. эта хрень спавнится редко.

**Comment by salwador** [comment]
fxd
