### ISSUE TITLE
Баг с оружием и машиной.

### ISSUE THREAD

**Issue by denisFo** [salwador/MTA-DayZ-Ultimate#9]
Очень дебильный баг. Бывает такое, что при выходе из машины нельзя поменять оружие, только после нажатия инвентаря или через какой то промежуток времени все становится как есть. Так же этот баг замечается находясь в близком расстоянии к палатке(происходит это , как я понял, из за того, что при появлении окна взаимодействия с палаткой мы непосредственно должны выбирать какое то действие, а то, что мы можем просто спрятаться за неё и хотим сменить оружие не предусмотрено). Мое предположение, что когда  выходишь из машины система как бы выбивает это окно взаимодействия(в котором написано "открыть инвентарь" "ремонт" ну и т.п.) и из за этого выходят неловкости со сменой оружия. Надеюсь более менее понятно написал. Баг бесит почти всех. 80% с ним сталкивались

**Comment by salwador** [comment]
@denisFo, повторяетесь, уже есть - но с более скудным описанием
https://github.com/salwador/MTA-DayZ-Ultimate/issues/4

И да, если появляется окно с действиями - это не баг, ибо так задумано.
Находишься рядом с объектом - появляются действия, отключается колёсико мыши.

**Comment by denisFo** [comment]
При выходе с авто такого окне нету. И даже отойдя от транспорта оружие сменить нельзя. Я считаю, что это как то связано. Предположение такое

**Comment by salwador** [comment]
@denisFo при выходе нельзя сменить оружие, и окно не появляется - верно?

**Comment by denisFo** [comment]
Верно

**Comment by salwador** [comment]
Fixed in 1.2.27+
