### ISSUE TITLE
Баг с текстуркой магазинов к АК-9, 9А-91, АК-9 NY и 9А-91 NY.

### ISSUE THREAD

**Issue by NeEvilMuffin** [salwador/MTA-DayZ-Ultimate#95]
Суть бага в том, что АК-9, 9А-91 и новогодние варианты имеют магазин от АС ВАЛа, и если на ВАЛе магазин отображается нормально, то на других стволах, использующих этот магазин, он отображается странно, а именно: текстура глушителя от ВАЛа накладывается на магазины.
Нормально выглядящий магазин:
![mta-screen_2018-02-11_15-46-00](https://user-images.githubusercontent.com/31744538/36073561-d9c1276a-0f43-11e8-8c69-0aec503140c0.png)
Магазины курильщика:
![mta-screen_2018-02-11_15-46-10](https://user-images.githubusercontent.com/31744538/36073567-0ab8a460-0f44-11e8-9122-c560cbaeac81.png) - 9А-91
![mta-screen_2018-02-11_15-46-17](https://user-images.githubusercontent.com/31744538/36073579-2d75b6d2-0f44-11e8-9a80-b1baca7a3dcf.png) - Новогодний 9А-91
![mta-screen_2018-02-11_15-46-27](https://user-images.githubusercontent.com/31744538/36073585-48da53a6-0f44-11e8-8ab6-b383920bde91.png) - Новогодний АК-9
Простого АК-9 у меня нет, но на нём магазин отображается так же, как и на вышеперечисленных стволах

**Comment by salwador** [comment]
Fixed in next version
