### ISSUE TITLE
Некорректный магазин на модели Colt CM-901

### ISSUE THREAD

**Issue by NeEvilMuffin** [salwador/MTA-DayZ-Ultimate#96]
5.56 магазины используются стволами типа М4 (ссо сд) (холо гл), М16А2 ЮСМС, Кольт ЦМ-901 , но у ЦМ-901 модель магазина отличается от модели магазина к М4 и т. д. , хотя по логике игры (сервера) они используют один и тот же патрон (магазин). Было бы неплохо заменить магазин, который стоит на ЦМ на стандартный магазин от М4. Вдобавок магазин, который стоит на ЦМ 20-ти зарядный, что уже противоречит логике и механике (или как это назвать) игры (сервеаа).
P.S. Да, это можно считать простой придиркой, и другие игроки даже не замечали этого недочёта, но всё же.
- Модель магазина ЦМ
![default](https://user-images.githubusercontent.com/31744538/36145846-afaa1db6-10c3-11e8-8170-1a41740956f9.png)
- модель магазина 5.56, который должен быть по логике игры (сервера)
![mta-screen_2018-02-13_13-13-43](https://user-images.githubusercontent.com/31744538/36145895-d605bc36-10c3-11e8-9d95-871a9b4e659b.png)

**Comment by salwador** [comment]
Да, действительно. Визуально у них должен быть один магазин

**Comment by salwador** [comment]
Fixed in next versions
