### ISSUE TITLE
Задержка при экипировании какого либо оружия

### ISSUE THREAD

**Issue by Private1337** [salwador/MTA-DayZ-Ultimate#97]
У многих это было.
Экипируешь оружие>>Начинаешь целить<<Зажимаешь>>Оружие не стреляет,а тебя сливают.
Баг активируется при быстрой экипировки и попыткой стрельбы
Хорошей работы and good luck <3

**Comment by salwador** [comment]
Это не баг... Элементарная задержка, следи за кругом на курсоре. :thinking:
