### ISSUE TITLE
Прицел на транквилизаторную винтовку

### ISSUE THREAD

**Issue by CrabbyAdei71** [salwador/MTA-DayZ-Ultimate#98]
Есть ли возможность прицепить прицел на транквилизаторную винтовку, она ВООБЩЕ не используется в игре, а будет снайперский прицел, будет веселее.

**Comment by salwador** [comment]
Закрывать не стану, посмотрим, но полезнее она от этого не становится. Подстрели ты его вдалеке, энивей со 100% вероятностью не добежишь, пока он в отключке.

**Comment by salwador** [comment]
Done in 1.4, forgotten closed
