### ISSUE TITLE
Плюсовая карма

### ISSUE THREAD

**Issue by CrabbyAdei71** [salwador/MTA-DayZ-Ultimate#99]
Почему 5000 порог кармы в игре, в отрицательную сторону удивительно далеко уходит, а в обратку нету, пусть и пвп сервер, но забавнее будет хвастать не сколько бандитов убил, а сколько героев.
Так же эту вкладку "убито героев" в табличку F5 впилить. 

P.S. Fred.

**Comment by salwador** [comment]
Смысла нет с кармы > 5000, однохуйственно героев настоящих нет, даже на сервере "Brown".
А учитывая что и геров то нет, смысла в доп. счётчике фрагов не будет, ибо в 99.9% значение будет 0.

**Comment by CrabbyAdei71** [comment]
Героев по этому случаю и нету, что набив 5000, мимо пробегающая кепка начнет ебать голову и стрелять со своего глока, карма убывает до 4200 и чтоб снова поднять порог надо искать бандита, а будь плюсовой порог выше, и убив 3х бандитов карма будет около 7000, убивая заядливую кепку героя ты не теряешь, а там  глядишь и инетерес появится, интерес к новому так и так будет

**Comment by salwador** [comment]
Да никто героя не набивает на бандитах, не напасёшь их столько. Почти каждый герой, поголовно - фармит карму на друзьях. Пока встретишь второго бандита, убьёшь тройку бичей.
